In [1]:
import numpy as np
import matplotlib.pyplot as plt
import qutip as qt
from jinja2 import pass_context
from qutip import Qobj
from scipy.interpolate import UnivariateSpline
import scipy.integrate as integrate
import scipy.special as special

from AQC import t_list


In [2]:
def f(t):
    return t

In [3]:
t=10
a=0.1
sx=qt.sigmax()
sz=qt.sigmaz()
sxx=sx*a
szz=sz*(f(t)-0.5)+sxx
print(szz)

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 9.5  0.1]
 [ 0.1 -9.5]]


In [4]:
a=np.array([[0, 0.5],[0.5, 0]])
a

array([[0. , 0.5],
       [0.5, 0. ]])

In [5]:
lol=qt.qeye(3)
# lol=qt.create(4,0)
lol1=lol*10
lol1

Quantum object: dims=[[3], [3]], shape=(3, 3), type='oper', dtype=Dia, isherm=True
Qobj data =
[[10.  0.  0.]
 [ 0. 10.  0.]
 [ 0.  0. 10.]]

In [6]:
a=0.8
c=2
b=11
def f(t):
    return t/2


data=[[c,a,0],[a,-c,0],[0,0,0]]
matrix=qt.Qobj(data)
matrix
data1=[[-1,0,0],[0,1,0],[0,0,f(6)]]
matrix1=qt.Qobj(data1)
total=matrix+(matrix1*b)
total



Quantum object: dims=[[3], [3]], shape=(3, 3), type='oper', dtype=Dense, isherm=True
Qobj data =
[[-9.   0.8  0. ]
 [ 0.8  9.   0. ]
 [ 0.   0.  33. ]]

In [7]:
np.pi

3.141592653589793

In [8]:
a = 0.1 #time-independent coupling constant
b = 2
c = 0.5
T = 400 #time evolution interval
args = {'T': T}
t=0
x=2
data=[[c,a,0],[a,-c,0],[0,0,0]]
H_static=qt.Qobj(data)
data1=[[-1,0,0],[0,x,0],[0,0,1*b]]
matrix1=qt.Qobj(data1)
def H_dynamic(b):
    return matrix1*b

In [9]:
def sqr_H(b):
    squard_H=H_dynamic(b)
    nump=squard_H.full()
    print(nump)
    return np.linalg.norm(nump,ord=2)

# print(H_dynamic(b))
print(sqr_H(b))
# print(H_dynamic(b)**2)
# lolll=H_dynamic(b)**2
# integrate.quad(sqr_H,0,1)

[[-2.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  4.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  4.+0.j]]
4.0


In [10]:
from scipy.integrate import quad
from scipy.differentiate import derivative

In [11]:
def function(x):
    return x**3

x=np.linspace(1,10,10)
array=[]
for l in x:
    x1=derivative(function,l)
    array.append(x1)


print(array)
# print()



[     success: True
      status: 0
          df: 2.9999999999999964
       error: 0.0
         nit: 2
        nfev: 11
           x: 1.0,      success: True
      status: 0
          df: 12.0
       error: 1.4210854715202004e-14
         nit: 2
        nfev: 11
           x: 2.0,      success: True
      status: 0
          df: 27.0
       error: 0.0
         nit: 2
        nfev: 11
           x: 3.0,      success: True
      status: 0
          df: 48.00000000000023
       error: 2.2737367544323206e-13
         nit: 2
        nfev: 11
           x: 4.0,      success: True
      status: 0
          df: 75.00000000000045
       error: 4.547473508864641e-13
         nit: 2
        nfev: 11
           x: 5.0,      success: True
      status: 0
          df: 107.99999999999909
       error: 9.094947017729282e-13
         nit: 2
        nfev: 11
           x: 6.0,      success: True
      status: 0
          df: 147.0
       error: 4.547473508864641e-13
         nit: 2
        nfev: 11
   

In [12]:
y=x**3
dy=np.diff(y)
yfirst=0.5*(y[:-1]+y[1:])
print(dy)
print(yfirst)

[  7.  19.  37.  61.  91. 127. 169. 217. 271.]
[  4.5  17.5  45.5  94.5 170.5 279.5 427.5 620.5 864.5]


In [13]:
def f(x):
    return x**3

lol = f(x)

i = integrate.quad(lol,0,1)
print(i[0])
print(f(1))


ValueError: invalid callable given

BACKUP

In [ ]:
#Integration
    # H_diff_1 = 1 / T
    # H_diff_2 = 0
    # H_diff_1 =derivative(lambda t: f(t, args), t)
    # H_diff_2 = derivative(lambda t: H_diff_1,t)
    # integration = (H_diff_2/g**2)+(7*(H_diff_1)**2/g**3)
    # H_integration = quad(integration,0,T)

    #Error_Threshold

    # error = (1/T)*((H_diff_1(f(0,args)+H_diff_1(f(1,args)))/g**2)+integration)
    # error.append(error)

BACKUP

In [ ]:
UP#initial hamiltonian
H_0=H_static+(f(t,args)*H_dynamic(b))
eigenvalue,eigenvector=H_0.eigenstates()
psi0=eigenvector[0]

#total hamiltonian
H_total=[H_static,[H_dynamic(b),f]]

#Solving
final = qt.sesolve(H_total, psi0, t_list, args=args)


BACKUP

In [ ]:
#Visualization
errors_fidelity = []
errors_norm = []
gap = []
ground=[]
first=[]
second=[]
error=[]

for i, t in enumerate(t_list):
    f_val = f(t, args)
    H_t = H_static + f_val * H_dynamic(b)

    # Get ideal eigenstates and energies
    evals, estates = H_t.eigenstates()
    g=evals[1]-evals[0]
    gap.append(g)

    #spectrum
    ground.append(evals[0])
    first.append(evals[1])
    second.append(evals[2])

    # Upper Bound for ERROR
    # first derivative
    m = 1
    def dH_1_norm(b):
        dH_1 = (H_dynamic(b)/T).full()
        return np.linalg.norm(dH_1,ord=2)

    def dH_1_norm_squared(b):
        dH_10 = (H_dynamic(b)/T).full()
        dH_11 = np.linalg.norm(dH_10,ord=2)
        return dH_11**2


    # dH_2 = 0
    dH_2_norm=0

    ub_1 = (1 / T) * m * 2 * dH_1_norm(b) / g ** 2
    ub_2 = (1 / T) * dH_2_norm / g ** 2
    # ub_3 = integrate.quad(dH_2_norm, 0, t)
    ub_4 = integrate.quad(dH_1_norm_squared, 0, t)
    # # ub_3=0

    total_equation = ub_1 + ub_2  + ((ub_4[0] * 7 * m * np.sqrt(m) / g ** 3))/T #should it be divided by T?
    error.append(total_equation)

    # Calculate Error (using Fidelity): 1 - |<psi_ideal | psi_evolved>|^2
    fidelity = np.abs(estates[0].overlap(final.states[i])) ** 2
    errors_fidelity.append(1 - fidelity)

    #Norm
    diff_vector = estates[0] - final.states[i]
    diff_vector_converted = diff_vector.full()
    vector_distance = np.linalg.norm(diff_vector_converted,ord=2)
    errors_norm.append(vector_distance)

In [ ]:
max_error=np.argmax(error)
time_at_error_peak=t_list[max_error]
error_value_at_peak=error[max_error]


plt.figure(figsize=(10,6))
plt.plot(t_list, error, color='pink')
plt.title('Error Upper Bound vs Time')
plt.xlabel('Timestep (t)')
plt.ylabel('Error')
plt.grid(True, which='both', linestyle='--', alpha=0.5)
# plt.ylim(0, 0.01)
plt.scatter(time_at_error_peak, error_value_at_peak, color='yellow', zorder=5)
plt.annotate(f'Peak: {error_value_at_peak:.5f}',
             xy=(time_at_error_peak, error_value_at_peak),
             xytext=(time_at_error_peak + 20, error_value_at_peak),
             arrowprops=dict(fc='teal', shrink=0.05,width=0.9, headwidth=5))

In [138]:
T=20
t_list=np.linspace(0,T,100)
meow=[]
for i, t in enumerate(t_list):

    def f(t):
        h = t**2
        return h
    meow.append(f(t))


meow[-1].item()

400.0

In [133]:
meow

[np.float64(0.0),
 np.float64(1.0),
 np.float64(4.0),
 np.float64(9.0),
 np.float64(16.0),
 np.float64(25.0),
 np.float64(36.0),
 np.float64(49.0),
 np.float64(64.0),
 np.float64(81.0),
 np.float64(100.0),
 np.float64(121.0),
 np.float64(144.0),
 np.float64(169.0),
 np.float64(196.0),
 np.float64(225.0),
 np.float64(256.0),
 np.float64(289.0),
 np.float64(324.0),
 np.float64(361.0),
 np.float64(400.0)]

In [134]:
difference=[]
for t in range(2,T+1):
    def f(t):
        h = (t)**2-(t-1)**2
        return h
    difference.append(f(t))


In [135]:
difference

[3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39]

In [142]:
difference22=[]
for i,t in enumerate(t_list):
    if 2 <= t <= T:
        def f(t):
            h = (t)**2-(t-1)**2
            return h.item()
        difference22.append(round(f(t),1))

print(difference22)

[3.0, 3.4, 3.8, 4.3, 4.7, 5.1, 5.5, 5.9, 6.3, 6.7, 7.1, 7.5, 7.9, 8.3, 8.7, 9.1, 9.5, 9.9, 10.3, 10.7, 11.1, 11.5, 11.9, 12.3, 12.7, 13.1, 13.5, 13.9, 14.4, 14.8, 15.2, 15.6, 16.0, 16.4, 16.8, 17.2, 17.6, 18.0, 18.4, 18.8, 19.2, 19.6, 20.0, 20.4, 20.8, 21.2, 21.6, 22.0, 22.4, 22.8, 23.2, 23.6, 24.1, 24.5, 24.9, 25.3, 25.7, 26.1, 26.5, 26.9, 27.3, 27.7, 28.1, 28.5, 28.9, 29.3, 29.7, 30.1, 30.5, 30.9, 31.3, 31.7, 32.1, 32.5, 32.9, 33.3, 33.7, 34.2, 34.6, 35.0, 35.4, 35.8, 36.2, 36.6, 37.0, 37.4, 37.8, 38.2, 38.6, 39.0]


In [116]:
difference1=[]
for i,t in enumerate(t_list):
    if 2 <= t <= T:
        def f(t):
            h = (t)**2-(t-1)**2
            return h
        difference1.append(f(t))
    else:
        pass

difference1

[np.float64(3.0),
 np.float64(5.0),
 np.float64(7.0),
 np.float64(9.0),
 np.float64(11.0),
 np.float64(13.0),
 np.float64(15.0),
 np.float64(17.0),
 np.float64(19.0)]

In [110]:
difference1

[np.float64(3.0),
 np.float64(5.0),
 np.float64(7.0),
 np.float64(9.0),
 np.float64(11.0),
 np.float64(13.0),
 np.float64(15.0),
 np.float64(17.0),
 np.float64(19.0)]

In [ ]:
def dH_1_norm_squared(b):
        dH_10 = (H_dynamic(b)/T).full()
        dH_11 = np.linalg.norm(dH_10,ord=2)
        return dH_11**2

    def bandgap_func(t):
        f_value=f(t, args)
        H_tt = H_static + f_value * H_dynamic(b)
        eigenvalue1,eigenvector1=H_tt.eigenstates()
        gg=eigenvalue1[1]-eigenvalue1[0]
        return gg.item()

In [ ]:
 total_equation = ub_1 + ub_2  + ((ub_4[0] * 7 * m * np.sqrt(m) / ub_44[0] ** 3))/T